---
- name: Update Macports and the ports tree
  become: true
  community.general.macports:
    selfupdate: true
  when: macports_selfupdate is true

- name: Upgrade installed ports
  become: true
  community.general.macports:
    upgrade: true
  when: macports_upgrade is true

- name: "Install ports"
  become: true
  community.general.macports:
    name: "{{ port }}"
    state: installed
  loop_control:
    loop_var: port
  loop:
    - curl-ca-bundle
    - python311
    - py311-ansible
    - py311-pip
    - py311-virtualenv
    - py311-wheel
    - mas
    - cowsay
    - the_silver_searcher
    - fzf
    - tree
    - yq
    - jq
    - htop
    - highlight
    - wget
    - gnupg2
    - hub
    - curl
    - unzip
    - coreutils
    - yubikey-manager
    - kubectl-1.27
    - openjdk20-oracle
