---
- name: Update Macports and the ports tree
  become: true
  community.general.macports:
    selfupdate: true
  when: macports_selfupdate is true

- name: Upgrade installed ports
  become: true
  community.general.macports:
    upgrade: true
  when: macports_upgrade is true

- name: "Install ports"
  become: true
  community.general.macports:
    name: "{{ port }}"
    state: installed
  loop_control:
    loop_var: port
  loop: '{{ macports_ports }}'
