---
- name: Install Unbound DNS server
  become: true
  community.general.macports:
    name: unbound
    state: installed
  notify:
    - Enable Unbound
    - Reload Unbound

- name: Create configuration file directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: root
    group: unbound
  become: true
  loop:
    - '{{ unbound_config_home }}/unbound.d/server'

- name: Copy unbound.conf file
  ansible.builtin.copy:
    src: unbound.conf
    dest: '{{unbound_config_home }}/unbound.conf'
    force: true
    owner: unbound
    group: unbound
    mode: '0644'
  become: true
  notify:
    - Reload Unbound

- name: Create dns zone for .docker TLD
  ansible.builtin.blockinfile:
    path: '{{ unbound_config_home }}/unbound.d/server/docker.conf'
    block: |
      local-zone: "docker" redirect
      local-data: "docker IN A 127.0.0.1"
    owner: unbound
    group: unbound
    mode: '0644'
    create: true
    marker: "# {mark} managed by ansible"
  become: true
  notify:
    - Reload Unbound

- name: Create resolver directory
  ansible.builtin.file:
    path: /etc/resolver
    state: directory
    mode: '0755'
    owner: root
  become: true

- name: Create dns zone for .docker TLD
  ansible.builtin.lineinfile:
    path: /etc/resolver/docker
    owner: root
    mode: '0644'
    create: true
    regexp: '^nameserver'
    line: nameserver 127.0.0.1
  become: true
  notify:
    - Flush DNS Cache

