---
- name: Install kubectl
  become: true
  community.general.macports:
    name: "kubectl-{{ kubectl_version }}"
    state: installed

- name: Set active kubectl version
  become: true
  ansible.builtin.shell:
    cmd: |
      /opt/local/bin/port select kubectl kubectl{{ kubectl_version }}

- name: Install krew
  become: true
  community.general.macports:
    name: krew
    state: installed

- name: Install helm
  become: true
  community.general.macports:
    name: "helm-{{ helm_version }}"
    state: installed

- name: Set active helm version
  become: true
  ansible.builtin.shell:
    cmd: |
      /opt/local/bin/port select helm helm{{ helm_version }}

- name: Download and install talosctl
  become: true
  ansible.builtin.get_url:
    url: 'https://github.com/siderolabs/talos/releases/download/v{{ talos_version }}/talosctl-darwin-arm64'
    dest: /usr/local/bin/talosctl
    mode: '755'

- name: Download and install clusterctl
  become: true
  ansible.builtin.get_url:
    url: 'https://github.com/kubernetes-sigs/cluster-api/releases/download/v{{ clusterctl_version }}/clusterctl-darwin-arm64'
    dest: /usr/local/bin/clusterctl
    mode: '755'

- name: Download Cilium CLI
  become: true
  ansible.builtin.get_url:
    url: 'https://github.com/cilium/cilium-cli/releases/download/v{{ cilium_cli_version }}/cilium-darwin-arm64.tar.gz'
    dest: /tmp/cilium.tar.gz
    mode: '755'

- name: Install Cilium CLI
  become: true
  ansible.builtin.shell:
    cmd: |
      tar xzvfC /tmp/cilium.tar.gz /usr/local/bin
      rm /tmp/cilium.tar.gz

- name: Download Hubble CLI
  become: true
  ansible.builtin.get_url:
    url: 'https://github.com/cilium/hubble/releases/download/v{{ hubble_cli_version }}/hubble-darwin-arm64.tar.gz'
    dest: /tmp/hubble.tar.gz
    mode: '755'

- name: Install Hubble CLI
  become: true
  ansible.builtin.shell:
    cmd: |
      tar xzvfC /tmp/hubble.tar.gz /usr/local/bin
      rm /tmp/hubble.tar.gz
