---
- name: Install asdf zsh plugin
  ansible.builtin.lineinfile:
    path: '{{ xdg_config_home }}/zsh/zsh_plugins.txt'
    line: 'asdf-vm/asdf kind:zsh'
    create: true

- name: Create global .tool-versions file
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.tool-versions"
    state: touch
    mode: '0600'

- name: Create data directory
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/asdf"
    state: directory
    mode: '0700'

- name: Set asdf environment variables
  ansible.builtin.lineinfile:
    path: '{{ xdg_config_home }}/env/asdf'
    regexp: '^{{ item.var }}='
    line: "{{ item.var }}={{ item.value }}"
    create: true
    mode: '0600'
  loop:
    - var: ASDF_DATA_DIR
      value: "{{ xdg_data_home }}/asdf"
    - var: ASDF_CONFIG_FILE
      value: "{{ xdg_config_home }}/asdfrc"
