---
- name: Install Starship prompt
  become: true
  community.general.macports:
    name: starship
    state: installed

- name: Install antidote
  ansible.builtin.git:
    repo: 'https://github.com/mattmc3/antidote.git'
    dest: '~/.local/antidote'
    depth: 1
    version: '{{ antidote_version }}'

- name: Create directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - '{{ xdg_config_home }}/env'
    - '{{ xdg_config_home }}/zsh'
    - '{{ xdg_data_home }}/zsh'

- name: Copy dotfiles to home directory
  include_tasks: copy_dotfile.yml
  loop:
  - zshenv
  - zshrc

- name: Copy files to home directory
  include_tasks: copy_file.yml
  loop:
    - src: paths.zsh
      dest: '{{ xdg_config_home }}/zsh'

- name: Create zsh_plugins.txt file
  ansible.builtin.lineinfile:
    path: '{{ xdg_config_home }}/zsh/zsh_plugins.txt'
    line: '{{ item }}'
    create: true
  loop:
    - Tarrasch/zsh-autoenv
    - zsh-users/zsh-syntax-highlighting
    - zsh-users/zsh-history-substring-search
    - zsh-users/zsh-completions
