---
- name: "Install tmux"
  become: true
  community.general.macports:
    name: tmux
    state: installed

- name: Set tmux plugin manager path
  ansible.builtin.lineinfile:
    path: '{{ xdg_config_home }}/env/tmux'
    regexp: '^TMUX_PLUGIN_MANAGER_PATH='
    line: "TMUX_PLUGIN_MANAGER_PATH={{ lookup('env', 'HOME') }}/.local/share/tmux/plugins"
    create: true
    mode: '0600'

- name: Copy tmux.conf to home directory
  ansible.builtin.copy:
    src: tmux.conf
    dest: ~/.tmux.conf
    force: true
    mode: '0600'
