---
- name: Install Neovim
  become: true
  community.general.macports:
    name: neovim
    state: installed

- name: Create neovim config directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0700'
  loop:
    - '{{ neovim_config_dir }}'
    - '{{ neovim_data_dir }}'

- name: 'Copy Neovim conf directory'
  ansible.builtin.copy:
    src: lazyvim/
    dest: "{{ neovim_config_dir }}"
    force: true
    mode: '0600'
